version: "3.9"
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports: ["3307:3306"]
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uapp", "-papp"]
      interval: 5s
      timeout: 3s
      retries: 20

  db-load:
    image: mysql:8.0
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: library
      DB_DIR: /db
    volumes:
      - ./db:/db:ro
      - ./scripts/load-sql.sh:/load-sql.sh:ro
    command: ["/bin/sh","-lc","/load-sql.sh"]
    restart: "no"

  mongo:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: library
    ports: ["27017:27017"]
    volumes:
      - mongo_data:/data/db
      # EITHER use your absolute path (quotes needed due to spaces)...
      - "/Users/phamlong/Desktop/RMIT/Database Application/smart-lib/smart-library-backend/db/reading_sessions.json:/docker-entrypoint-initdb.d/reading_sessions.json:ro"
      # ...OR (better) keep it in-repo:
      # - ./db/reading_sessions.json:/docker-entrypoint-initdb.d/reading_sessions.json:ro
      - ./scripts/init-mongo.sh:/docker-entrypoint-initdb.d/10-init-mongo.sh:ro
    healthcheck:
      test: ["CMD-SHELL", "mongosh --username root --password root --authenticationDatabase admin --eval 'db.adminCommand({ ping: 1 })' --quiet"]
      interval: 5s
      timeout: 3s
      retries: 30

  api:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
      db-load:
        condition: service_started
      mongo:
        condition: service_healthy
    env_file: [.env]
    environment:
      MONGO_URI: mongodb://root:root@mongo:27017
      MONGO_DB: library
    ports: ["8080:8080"]
    volumes:
      - .:/usr/src/app
    command: ["npm","run","dev"]

volumes:
  mysql_data:
  mongo_data:
